### PR TITLE
Better buttons

### PR DESCRIPTION
**Pull request by lindlands**
-Optional parameter added for extra styling
-Added dark blue secondary button

### CODE REVIEW

**Review by dylantompkins — APPROVED** [review]
LGTM

**Comment by dylantompkins** [comment]
Wait for all to approve before merge so that lindsay can complete the individual asgn

**Review by k4yluh — APPROVED** [review]
Looks good! Hard to say there is anything to change as I don't know what the button looks like in usage 💯

**Review by JonasSchiessl — APPROVED** [review]
looks good

**Review by meganfung38 — APPROVED** [review]
Looks great :) Good job-- excited to see everything come together!

**Pull request merged**
