### PR TITLE
Authorization in frontend

### PR DESCRIPTION
**Pull request by JonasSchiessl**
PR Title: Authorization in frontend

1. Issue #125  [Link ](https://github.com/Green-Kittens/bathroom-finder-frontend/issues/125)

2. Summary: 
- The issue covers the SignIn and SignUp flow, handling Authorization in the frontend. 
- This adds protected features like creating reviews, liking, replies and most importantly creating new bathrooms. 
- Main attributes are extensive error handling, multiple sign in options, registration, forgot password with password reset, email verification, and password strength checking. 
- This is important for production to create and manage the users but also add security to the app. 

4. Changes: 
- Some changes have been made to the file structure to move the screen outside the navigation folder. Authentication was also added to the navbar to limit the features you can use in it, like adding a location. 

6. Potential Fixes:
- Found a potential fix to the Ionicon errors in the navbar but has not been implemented. 

8. Notes for the reviewers: 
- Check the login, register and forgot password as those have the most changes
- There should be 3 new components for this issue handling sign in with different orginizations
- Check for error handling. 
- no special setup is required

9. Future Improvements

### CODE REVIEW

**Review by lindlands — CHANGES_REQUESTED** [review]
I like the new error messages and the greyed-out button component. Sign in with Microsoft still works for me.
Couple fixes though:
- I can still see the error message "Please fill out all fields" even when there is both a username and password. The message disappears when Login is pressed and does not reappear when the password is deleted.
- I can still press Login when my email is not valid
- "Don't have an account? Register" overlaps with the sign in buttons at the bottom.
- "Don't have an account? Register" moves up with the keyboard so it appears above the password box.

**Comment by JonasSchiessl** [comment]
> I like the new error messages and the greyed-out button component. Sign in with Microsoft still works for me. Couple fixes though:
> 
> * I can still see the error message "Please fill out all fields" even when there is both a username and password. The message disappears when Login is pressed and does not reappear when the password is deleted.
> * I can still press Login when my email is not valid
> * "Don't have an account? Register" overlaps with the sign in buttons at the bottom.
> * "Don't have an account? Register" moves up with the keyboard so it appears above the password box.

I fixed all of those except the fill out fields thing because the messages depend on the users input but for some reason deleting the text doesn't count so theres nothing i can do. It reappears if you edit the email while the password is empty.

**Comment by dylantompkins** [comment]
When it is time to merge, ping me and I will override the sonarcloud fail and merge it. Please have everything else passing before asking me to merge.

**Review by lindlands — CHANGES_REQUESTED** [review]
Couple issues:
- On Register screen: getting the error "Passwords don't match" even with matching passwords.
- On Forgot Password screen: cannot press submit button when I put my email address in

"Don't have an account? Register" No longer pops up with keyboard! There still are issues with its overlap with "Email Code Login"--do you want me to fix that real quick since I can check it with my phone?

**Review by lindlands — CHANGES_REQUESTED** [review]
Still having problems with passwords not matching as well as Register overlapping with Email Code.

**Comment by JonasSchiessl** [comment]
> Still having problems with passwords not matching as well as Register overlapping with Email Code. Forgot Password is working now though!

Should be fixed now, but I'm using android studio to simulate an android I don't see the same issue you are having, so maybe that is something you could work on after the merge? I don't think this is p0 to get all different screen resolutions and androids to work.

**Review by lindlands — CHANGES_REQUESTED** [review]
Still having the same issue with passwords "not matching". The error does disappear on modification of the email for some reason. Attached below is video.

https://github.com/Green-Kittens/bathroom-finder-frontend/assets/71728910/af5eeac7-f89b-4818-8d44-5853cd638cef

**Review by lindlands — APPROVED** [review]
Nice work! 
Apparently Password-12345 was found in a data breach haha

**Pull request merged**
