### PR TITLE
Azure upload

### PR DESCRIPTION
**Pull request by dylantompkins**
# Checklist

- [x] Have I clearly explained the issue or feature request that this PR addresses?
- [x] Have I provided where new implementations for the PR have been made?
- [x] Did I highlight any areas that may need special attention during the review?
- [x] If applicable, did I specify any setup requirements or dependencies for testing?
- [x] Have I disclosed any known issues or limitations related to this PR? Did I explain why these limitations exist and how they might be addressed in the future?
- [x] Have I provided enough context for someone unfamiliar with the issue or the codebase to understand the changes?
- [x] Have I assigned appropriate reviewers who are knowledgeable about the changes? Did I consider including team members who might be affected or interested in the changes?

# Description

Closes green-kittens/bathroom-finder-backend#24

## Summary

upload images to cloud storage through the backend and display on facilities

## Expectations

1. log in
2. go to facility form
3. put your pin somewhere you will be able to find it easily (not an existing spot)
4. add image(s)
5. write something in description (required otherwise 400 error on createBathroom)
6. submit
7. go find your pin
8. click on it
9. see your image in the carosel!!!

## Additional Comments/Notes

No idea what the state of creating a review is rn, pretty sure Megan has a PR open for that. This is for creating facilities.

### CODE REVIEW

**Review by lindlands — CHANGES_REQUESTED** [review]
Set bathroom, uploaded 5 images. On submit, received the following errors:
AxiosError uploadImage [as a pop-up]
Error creating bathroom: undefined
[Console Warning] Possible unhandled promise rejection

image

**Comment by dylantompkins** [comment]
> Set bathroom, uploaded 5 images. On submit, received the following errors

Was not able to reproduce given these instructions.

Can you please reproduce this error and paste the console logs?

**Comment by dylantompkins** [comment]
Actually it's unclear what

> Set bathroom

means.

I opened the facility form, moved the marker, added 5 pictures from my camera, wrote a short description, and then submitted without error.

**Comment by lindlands** [comment]
Still isn't working on my end, no matter how many images are uploaded. 
Filled out bathroom form completely to get those errors on sumbit.

**Review by lindlands — APPROVED** [review]
Nice work!
Issue was resolved through magic

**Pull request merged**
