### PR TITLE
updated controller

### PR DESCRIPTION
**Pull request by JonasSchiessl**
PR Title: [Brief Description] (Linking The UserID that gets created from Clerk to store it in the database for all sorts of user functions.)zz

# Checklist

- [ ] Have I clearly explained the issue or feature request that this PR addresses?
- [ ] Have I provided where new implementations for the PR have been made?
- [ ] Did I highlight any areas that may need special attention during the review?
- [ ] If applicable, did I specify any setup requirements or dependencies for testing?
- [ ] Have I disclosed any known issues or limitations related to this PR? Did I explain why these limitations exist and how they might be addressed in the future?
- [ ] Have I provided enough context for someone unfamiliar with the issue or the codebase to understand the changes?
- [ ] Have I assigned appropriate reviewers who are knowledgeable about the changes? Did I consider including team members who might be affected or interested in the changes?

## Description
This isn't necessarily an issue as described, but an important feature to fully connect the frontend and backend with the user management. The reason the calls are made in main is to circumvent the many different login options we have so no matter what way you login, your user ID will be checked to the database and if you don't have any data it will create it. 

## Summary
Checks if database has user if not will create a user in the database using the clerk id. 

## Expectations
 In theory, it should work as long as the changes in the backend get pushed first, so please check out that pull request first. 

## Additional Comments/Notes
 I tested the methods using hopscotch but not sure how well the frontend will handle this.

### CODE REVIEW

**Review by kaylantran — COMMENTED** [review]
What are these changes attempting to do? -- why are you having register user have userID passing in now? How would it have a userID already before they even register?

**Comment by JonasSchiessl** [comment]
> What are these changes attempting to do? -- why are you having register user have userID passing in now? How would it have a userID already before they even register?

We aren't actually handling the registration, we are using the ID that is given from clerk to be the UserID that way you can easily interchange data. Right now the User isn't connected at all to the database.

**Comment by JonasSchiessl** [comment]
To Sum up, we check if there is a logged-in session, if there is we make a call to get the user profile using the Clerk ID, if it isn't in the database we will just call the register user to create the user in the database.

**Review by kaylantran — APPROVED** [review]
Good!

**Pull request merged**
