### PR TITLE
Issue #120 and #45: Put brs on map

### PR DESCRIPTION
**Pull request by meganfung38**
Issue #120: get all bathroom facilities from db using controller function and map each facility into a marker on the map in main.tsx
Issue #45: each facility marker on main.tsx navigates to the facility profile screen

- Expectations: 
   - a marker for every bathroom facility in the db should render as a marker component on main.tsx
   - on press: marker should navigate to the facility profile page. A separate PR will be created to show the bathroom facility's data for its profile
   - removed .env file and modified env.ts so that controller works with azure
   - NOTE: the only bathroom facility in the db right now is at coordinates, [64, 72], so you will need to zoom out to see the marker on the map-- you should expect to see it in ASIA
  
- Implementation of development are made on main.tsx

- Additional Comments: you may have to change the following files according to how you will call/ run the backend:
   - env.ts

### CODE REVIEW

**Comment by dylantompkins** [comment]
👀 
Attempted to look at this to review, but there are merge conflicts

**Comment by dylantompkins** [comment]
please fix

```
The following packages should be updated for best compatibility with the installed expo version:
  @react-native-community/datetimepicker@8.0.0 - expected version: 8.0.1
  expo@51.0.5 - expected version: ~51.0.8
  expo-image-picker@15.0.4 - expected version: ~15.0.5
  jest-expo@51.0.1 - expected version: ~51.0.2
Your project may not work correctly until you install the expected versions of the packages.
```

**Comment by dylantompkins** [comment]
need to solve key warning too

**Comment by JonasSchiessl** [comment]
Can you add maybe one or two more bathrooms so we can test if it works with multiple bathrooms at once on the map. Maybe make two that are closer to the user.

**Review by JonasSchiessl — APPROVED** [review]
Looks good, note for future you add a maximum range

**Review by kaylantran — APPROVED** [review]
Nice!! Excited for this feature :))

**Review by dylantompkins — APPROVED** [review]

**Review by lindlands — APPROVED** [review]
Nice work!

**Pull request merged**
