### PR TITLE
Implementation: Image Carousel on Facility Profile

### PR DESCRIPTION
**Pull request by meganfung38**
# Checklist

- [x] Have I clearly explained the issue or feature request that this PR addresses?
- [x] Have I provided where new implementations for the PR have been made?
- [x] Did I highlight any areas that may need special attention during the review?
- [x] If applicable, did I specify any setup requirements or dependencies for testing?
- [x] Have I disclosed any known issues or limitations related to this PR? Did I explain why these limitations exist and how they might be addressed in the future?
- [x] Have I provided enough context for someone unfamiliar with the issue or the codebase to understand the changes?
- [x] Have I assigned appropriate reviewers who are knowledgeable about the changes? Did I consider including team members who might be affected or interested in the changes?

# Description

## Summary
Issue #140:
- originally the facility profile screen image display was for a single image. Since we allow a user to upload multiple images to a facility on the facility form, this new implementation supports the display of all images uploaded to the facility. 

## Expectations
- files changed: facility-profile.tsx
- steps for testing: 
   1. navigate to a facility profile 
   2. see that the image display is now in a image carousel (visually, the image carousel should look very similar to the one implemented in the facility and review forms-- only difference is that there is no option to delete an image, like there is on the facility and review forms when you click on the image)
- upon clicking on an image in the carousel, expect to see a modal pop up of the image with an "x" button on the top right corner

## Additional Comments/Notes
- did not use Carousel.tsx component as user should not be able to delete an image from the carousel

### CODE REVIEW

**Comment by dylantompkins** [comment]
I agree with sonarcloud saying that this is too much duplicate code. The carousel is already a component. Please use that.

**Review by dylantompkins — CHANGES_REQUESTED** [review]
pass sonarcloud

**Comment by meganfung38** [comment]
@dylantompkins I know there is a lot of duplicate code for the imageCarousel implementation on facility profile but the component created supports the ability for a user to delete an image from the carousel which should not be supported functionality on the facility profile. Furthermore, the imageCarousel component requires a componentId for images to be passed into the component, which in this case will not work-- the images being passed are from a get request for a BathroomProfile.

**Comment by dylantompkins** [comment]
> but the component created supports the ability for a user to delete an image from the carousel which should not be supported functionality on the facility profile.

You should be able to add an optional parameter to the review component to disable the button for deleting.

> Furthermore, the imageCarousel component requires a componentId for images to be passed into the component, which in this case will not work-- the images being passed are from a get request for a BathroomProfile.

I'll admit I don't have a ton of context here, but I'd imagine one of two solutions could work:
1. Map over the images you want to pass into the review component and transform them into the proper format before passing them. Possibly adding a dummy id
2. Modify the type of the parameter for the Review component to be usable in both scenarios, and then do any required transformation inside the component.

**Comment by dylantompkins** [comment]
⬆️ Megan convinced me in slack DM that it's not worth the time this late in the game to modify the review component

**Review by dylantompkins — APPROVED** [review]

**Pull request merged**
